#!/bin/bash

#read eeprom
eeprom=/sys/devices/platform/ocp/44e0b000.i2c/i2c-0/0-0050/eeprom
hexdump -C -v -n 128 -s 0 /sys/devices/platform/ocp/44e0b000.i2c/i2c-0/0-0050/eeprom > /var/bbb_log/sn.log

if [ $? -eq 0 ];then
	cat /var/bbb_log/sn.log | tail -n +2 | head -n 1 > /var/bbb_log/sn2.log
	exit 0
else
	exit 1
fi


